name = "r2-image-viewer-tinygo"
main = "./build/worker.mjs"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[build]
command = "make build"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'r2-image-viewer'
preview_bucket_name = 'r2-image-viewer-dev'