name = "go-cron"
main = "./build/worker.mjs"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[triggers]
crons = ["* * * * *"]

[build]
command = "make build"
