name = "env"
main = "./build/worker.mjs"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[build]
command = "make build"

# declare environment variables and assign values
# https://developers.cloudflare.com/workers/platform/environment-variables/
[vars]
MY_ENV = 'my env value'
