name = "queues-producer"
main = "./build/worker.mjs"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[[queues.producers]]
queue = "my-queue"
binding = "QUEUE"

[build]
command = "make build"
