name = "service-bindings"
main = "./build/worker.mjs"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
services = [
    { binding = "hello", service = "hello" }
]

[build]
command = "make build"
