name = "fetch-event"
main = "./build/worker.mjs"
compatibility_date = "2023-02-24"

# setup route and uncomment
# routes = [
#     { pattern = "example.com/*", zone_name = "example.com" }
# ]

[build]
command = "make build"
