name = "fetch-event"
main = "./build/worker.mjs"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

routes = [
    { pattern = "example.com/*", zone_name = "example.com" }
]

[build]
command = "make build"
